import { useEffect, useState } from 'react';
import { FlaskConical, Map, Radio } from 'lucide-react';

import { Card, Badge, LoadingState } from '@/components/ui';
import OperationSummaryCard from '@/components/OperationSummaryCard';
import OperationStageTracker from '@/components/OperationStageTracker';
import MapPreview from '@/components/MapPreview';
import MapLegend from '@/components/MapLegend';
import {
  getDemoOperation,
  getDemoOperationStages,
  getDemoOperationLocations,
  getDemoOperationRoute,
} from '@/services/operationDetailService';

/**
 * Operations — the Operations Control Center (`/app/operations`).
 *
 * Shows a single demo rescue operation (RS-1024) end to end: a status
 * summary, a 7-stage progress tracker, and a map area with an illustrative
 * route. Everything on this page is frontend-only mock data (see
 * data/operationDetail.js) fetched through operationDetailService, the same
 * mock-request pattern used by the rest of the app. There is no backend, no
 * live GPS tracking, and no real-world rescue-partner dispatch behind it —
 * every illustrative figure (stage timestamps, ETA, route, map position) is
 * called out as demo information.
 */
export default function Operations() {
  const [operation, setOperation] = useState(null);
  const [stages, setStages] = useState(null);
  const [locations, setLocations] = useState(null);
  const [route, setRoute] = useState(null);

  useEffect(() => {
    let active = true;

    getDemoOperation().then((data) => active && setOperation(data));
    getDemoOperationStages().then((data) => active && setStages(data));
    getDemoOperationLocations().then((data) => active && setLocations(data));
    getDemoOperationRoute().then((data) => active && setRoute(data));

    return () => {
      active = false;
    };
  }, []);

  return (
    <div className="animate-fade-up space-y-6 lg:space-y-8">
      {/* ---------- Page header ---------- */}
      <div>
        <div className="flex flex-wrap items-center gap-2.5">
          <h1 className="text-xl font-bold tracking-tight text-content sm:text-2xl">
            Operations Control Center
          </h1>
          <Badge tone="predicted" icon={FlaskConical} size="sm">
            DEMO / MOCK OPERATION
          </Badge>
        </div>
        <p className="mt-1.5 text-sm text-muted">
          A single illustrative rescue, shown end to end — status, progress, and location.
        </p>
      </div>

      {/* ---------- Operation summary ---------- */}
      {operation === null ? (
        <Card>
          <Card.Body>
            <LoadingState label="Loading operation…" />
          </Card.Body>
        </Card>
      ) : (
        <OperationSummaryCard operation={operation} />
      )}

      <div className="grid grid-cols-1 gap-6 lg:gap-8 xl:grid-cols-2">
        {/* ---------- Operation progress ---------- */}
        <Card>
          <Card.Header
            icon={Radio}
            title="Operation Progress"
            subtitle="Created → AI Analyzed → Matched → Partner Assigned → Pickup Started → In Transit → Delivered."
          />
          <Card.Body>
            {stages === null ? (
              <LoadingState label="Loading progress…" />
            ) : (
              <>
                <OperationStageTracker stages={stages} />
                <p className="mt-4 border-t border-line pt-3 text-[11px] text-faint">
                  Timestamps are hardcoded, illustrative values for this demo — not a live or
                  auto-refreshing feed.
                </p>
              </>
            )}
          </Card.Body>
        </Card>

        {/* ---------- Route / map area ---------- */}
        <Card>
          <Card.Header
            icon={Map}
            title="Route (Demo)"
            subtitle="Illustrative route from Hotel XYZ to NGO A, Indiranagar, Bengaluru."
          />
          <Card.Body className="space-y-4">
            {locations === null ? (
              <LoadingState label="Loading map…" />
            ) : (
              <>
                <MapPreview locations={locations} route={route} zoom={14} />
                <MapLegend />
                <p className="text-[11px] text-faint">
                  Dashed line is a mock, hand-placed route for this demo — not generated by a
                  routing engine. Positions, the ETA, and the rescue partner marker are
                  illustrative only and are not a live GPS feed or vehicle location.
                </p>
              </>
            )}
          </Card.Body>
        </Card>
      </div>
    </div>
  );
}
